import type { Notice, Program, RehearsalItem, Song, User } from "./types";

export const CURRENT_USER: User = {
  id: "u1",
  name: "Ministério",
  role: "integrante",
  avatarInitials: "LF",
};

export const SONGS: Song[] = [
  {
    id: "s1",
    name: "Plano Melhor",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 4,
    lastPlayed: "2026-09-27",
    lastSolo: "Juliana",
    isNew: false,
  },
  {
    id: "s2",
    name: "Vento do Espírito",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 6,
    lastPlayed: "2026-09-20",
    lastSolo: "Gabi",
    isNew: false,
  },
  {
    id: "s3",
    name: "Lugar Seguro",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 3,
    lastPlayed: "2026-09-13",
    lastSolo: "Juliana",
    isNew: false,
  },
  {
    id: "s4",
    name: "Me Atraiu",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 8,
    lastPlayed: "2026-09-27",
    lastSolo: "Gabi",
    isNew: false,
  },
  {
    id: "s5",
    name: "Começo, Meio e Fim",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 2,
    lastPlayed: "2026-09-06",
    lastSolo: "Quezia",
    isNew: false,
  },
  {
    id: "s6",
    name: "Escolhido",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 5,
    lastPlayed: "2026-09-20",
    lastSolo: "Henrique",
    isNew: false,
  },
  {
    id: "s7",
    name: "Estevão",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 1,
    lastPlayed: null,
    lastSolo: "Quezia",
    isNew: true,
  },
  {
    id: "s8",
    name: "Ao Único",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 7,
    lastPlayed: "2026-08-30",
    lastSolo: "Juliana",
    isNew: false,
  },
  {
    id: "s9",
    name: "Yeshua",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 3,
    lastPlayed: "2026-09-13",
    lastSolo: "Gabi",
    isNew: false,
  },
  {
    id: "s10",
    name: "Digno",
    artist: null,
    reference: null,
    tone: null,
    cifraStatus: "PENDENTE",
    cifraContent: null,
    lyrics: null,
    listenUrl: null,
    timesPlayed: 4,
    lastPlayed: "2026-09-06",
    lastSolo: "Quezia",
    isNew: false,
  },
];

export const DEMO_PROGRAM: Program = {
  id: "p1",
  title: "Próximo Culto",
  dateLabel: "03 OUT",
  weekday: "Sábado",
  dateISO: "2026-10-03",
  items: [
    {
      id: "pi1",
      songId: "s1",
      position: 1,
      solo: "Juliana",
      tone: null,
      status: "PENDENTE",
      notes: null,
      cifraStatus: "PENDENTE",
    },
    {
      id: "pi2",
      songId: "s2",
      position: 2,
      solo: "Gabi",
      tone: null,
      status: "PENDENTE",
      notes: null,
      cifraStatus: "PENDENTE",
    },
    {
      id: "pi3",
      songId: "s3",
      position: 3,
      solo: "Juliana",
      tone: null,
      status: "PENDENTE",
      notes: null,
      cifraStatus: "PENDENTE",
    },
    {
      id: "pi4",
      songId: "s4",
      position: 4,
      solo: "Gabi",
      tone: null,
      status: "PENDENTE",
      notes: null,
      cifraStatus: "PENDENTE",
    },
    {
      id: "pi5",
      songId: "s5",
      position: 5,
      solo: "Quezia",
      tone: null,
      status: "PENDENTE",
      notes: null,
      cifraStatus: "PENDENTE",
    },
    {
      id: "pi6",
      songId: "s6",
      position: 6,
      solo: "Henrique / Quezia",
      tone: null,
      status: "PENDENTE",
      notes: null,
      cifraStatus: "PENDENTE",
    },
    {
      id: "pi7",
      songId: "s7",
      position: 7,
      solo: "Quezia",
      tone: null,
      status: "PENDENTE",
      notes: null,
      cifraStatus: "PENDENTE",
    },
  ],
};

export const REHEARSALS: RehearsalItem[] = DEMO_PROGRAM.items.map((item) => ({
  id: `r-${item.id}`,
  songId: item.songId,
  solo: item.solo,
  tomOriginal: null,
  tomEnsaio: null,
  tomAprovado: null,
  status: "PENDENTE" as const,
}));

export const NOTICES: Notice[] = [
  {
    id: "n1",
    title: "Ensaio de sábado",
    date: "2026-10-04",
    message: "Ensaio às 18h. Tragam instrumentos afinados e cifras atualizadas.",
    responsible: "Ministério de Louvor",
  },
  {
    id: "n2",
    title: "Chegar 30 min antes",
    date: "2026-10-03",
    message: "No culto de sábado, toda a equipe deve chegar 30 minutos antes para oração e alinhamento.",
    responsible: "Liderança",
  },
  {
    id: "n3",
    title: "Nova música no repertório",
    date: "2026-10-01",
    message: "Estevão entrou na programação. Revisem a referência e aguardem o tom aprovado.",
    responsible: "Ministro",
  },
  {
    id: "n4",
    title: "Tom alterado — pendente",
    date: "2026-09-30",
    message: "Alguns tons ainda estão PENDENTES. Não inventem — aguardem aprovação no ensaio.",
    responsible: "Ministro",
  },
];

export const MINISTER_PIN = "2626";

export function getSongById(id: string): Song | undefined {
  return SONGS.find((s) => s.id === id);
}
